### ISSUE TITLE
beatmap 1231758: java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"

### ISSUE THREAD

**Issue by Tillerino** [Francesco149/koohii#6]
Something isn't working with beatmap 1231758. Any ideas?

```java
java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.github.francesco149.koohii.Koohii$Parser.timing(Koohii.java:498)
        at com.github.francesco149.koohii.Koohii$Parser.map(Koohii.java:592)
```

**Comment by omkelderman** [comment]
ok wtf ppy plz...
 ![wtf](https://omk.pics/1/Kbnff.png)

**Comment by Francesco149** [comment]
lol what ?????
guess we'll have to swallow invalid lines

**Comment by omkelderman** [comment]
note that as I discovered in Francesco149/oppai-ng#29 invalid lines in HitObjects section *do* fail to load in the osu client and thus maybe should fail here as well 🤔 (unless you dont care about swallowing more bullshit than peppy does)

**Comment by Francesco149** [comment]
since we keep getting evidence that there is nothing to trust about .osu files in the wild i'd rather just swallow all invalid lines and hope for the best
